- name: Deploy Azure ARM template.
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        state: present
        resource_group_name: terraformtest
        template: "{{ lookup('file', './arm_windows.json') }}"
        parameters:
          adminUsername:
            value: "merril"
          adminPassword:
            value: "Test123*"
          dnsLabelPrefix:
            value: "merril"

